---
- name: Add EPEL repository
  yum:
    name: epel-release
    state: present
    #https://developer.bskyb.com/wiki/display/cloud/Register+with+RHEL+Satellite

- name: Install basic packages
  package:
    name: ['vim','bash-completion','tmux','tree','htop','wget','unzip','curl','git']
    state: present

- name: Install Java 8
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Add tomcat group
  group:
    name: tomcat

- name: Add "tomcat" user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
    system: yes

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"

- name: Create a tomcat directory
  file:
    path: /data/tomcat/usr/share/tomcat
    state: directory
    owner: tomcat
    group: tomcat


- name: Create a tomcat directory
  file:
    path: /data/tomcat
    state: directory
    owner: tomcat
    group: tomcat


- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /data/tomcat/usr/share/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /data/tomcat/usr/share/tomcat/bin

- name: cop.comy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: cop.comy server.xml service file
  template:
    src: templates/server.xml.j2
    dest: /data/tomcat/usr/share/tomcat/conf/server.xml

- name: cop.comy startup
  template:
    src: templates/startup.sh.j2
    dest: /data/tomcat/usr/share/tomcat/bin/startup.sh

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: permissions to splunk
  file:
    state: directory
    path: '/var/log/tomcat/'
    mode: '0755'

- name: Set UI access credentials
  template:
    src: tomcat-users.xml.j2
    dest: /data/tomcat/usr/share/tomcat/conf/tomcat-users.xml
  notify: restart tomcat
...